### ISSUE TITLE
Request for Testing Code in [GLORY]

### ISSUE THREAD

**Issue by wang-hui21** [tinyrolls/GLORY#2]
Dear friend,

I hope this email finds you well. My name is Hui Wang, and I am currently working on News Recommendations . Recently, I came across your GLORY repository, and I am impressed by the work you have done .

I believe having access to the corresponding testing code would greatly assist me in my learning process. I have already gone through the existing documentation and source code, but having a dedicated testing code would provide more insights.

If it is possible, could you please share any testing code to test a trained model? This would be immensely helpful for my project, and I am eager to ensure that I am using your code in the most effective and correct way.

Thank you for your time, and I appreciate your hard work on this valuable project. I understand that you may be busy, so any guidance or assistance you can provide will be highly appreciated.

Looking forward to your positive response.

Best regards,

Hui Wang
1024099045@qq.com
Lanzhou University

**Comment by tinyrolls** [comment]
Thank you for your attention. 
You can refer to the load checkpoint part of my code to test the trained models.

**Comment by wang-hui21** [comment]
> Thank you for your attention. You can refer to the load checkpoint part of my code to test the trained models.

Thank you for your response! I have already resolved the issue.
